from typing import Any

from fastapi import FastAPI
from pydantic import BaseModel, Field


SERVICE_VERSION = "stub-v1"

app = FastAPI(title="MaternaLink AI Service", version=SERVICE_VERSION)


class FlexiblePayload(BaseModel):
    data: dict[str, Any] = Field(default_factory=dict)


@app.get("/health")
def health() -> dict[str, str]:
    return {"service": "maternalink-ai-service", "version": SERVICE_VERSION, "status": "ok"}


@app.post("/layer0/extract-symptoms")
def extract_symptoms(payload: FlexiblePayload | None = None) -> dict[str, Any]:
    source_text = ""
    if payload:
        source_text = str(payload.data.get("text") or payload.data.get("complaint") or "")

    symptoms = []
    if "pusing" in source_text.lower():
        symptoms.append({"code": "G05", "label": "Pusing", "confidence": 0.75})

    return {"source": "FASTAPI_STUB", "modelVersion": SERVICE_VERSION, "symptoms": symptoms}


@app.post("/layer1/forecast-demand")
def forecast_demand(payload: FlexiblePayload | None = None) -> dict[str, Any]:
    return {"source": "FASTAPI_STUB", "modelVersion": SERVICE_VERSION, "predictions": []}


@app.post("/layer2/allocate")
def allocate(payload: FlexiblePayload | None = None) -> dict[str, Any]:
    return {"source": "FASTAPI_STUB", "modelVersion": SERVICE_VERSION, "allocations": []}


@app.post("/layer2/explain")
def explain(payload: FlexiblePayload | None = None) -> dict[str, Any]:
    return {
        "source": "FASTAPI_STUB",
        "modelVersion": SERVICE_VERSION,
        "explanation": "Fallback explanation generated by FastAPI stub. Full AI model integration is planned for next phase.",
    }
