import type { AbstractIntlMessages } from 'next-intl';
import { defaultLocale, type AppLocale } from './config';

const en = {
  common: {
    home: 'Home', settings: 'Settings', help: 'Help', logout: 'Logout', language: 'Language', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', detail: 'Detail', active: 'Active', inactive: 'Inactive', actions: 'Actions', status: 'Status', name: 'Name', role: 'Role', facility: 'Facility', email: 'Email', username: 'Username', password: 'Password', search: 'Search', syncingAi: 'Syncing AI Data', syncAi: 'Sync AI Master'
  },
  nav: {
    dashboard: 'Dashboard', healthCenters: 'Health Centers', users: 'User Accounts', medicines: 'Medicine List', facilityProfiles: 'Facility Profiles', patientQueue: 'Patient Queue', patients: 'Patient List', forecastCalendar: 'Prediction Calendar', medicineNeeds: 'Medicine Needs', ifkDashboard: 'IFK Dashboard', recommendations: 'Recommendations', clinics: 'Clinics', environment: 'Environment', decisionHistory: 'Decision History', deliveries: 'Delivering'
  },
  admin: {
    superAdmin: 'SUPER ADMIN', settingsTitle: 'Admin Settings', helpTitle: 'Admin Help', settingsSession: 'Active login cookie', helpBody: 'All admin data is saved directly to the backend. Use add, edit, delete, sync, filter, and export actions in each module.', dashboardTitle: 'Admin Dashboard', dashboardSubtitle: 'MaternaLink master data summary from the active database', lastUpdated: 'Last updated', totalHealthCenters: 'Total Health Centers', totalUsers: 'Total Users', totalMedicines: 'Total Medicines', inactiveAccounts: 'Inactive Accounts', last30Days: '+{count} / 30 days', needsReview: 'Needs review', safe: 'Safe', recentActivity: 'Recent Activity', allActivity: 'All Activity', loadMoreActivities: 'Load 10 More Activities', noAuditLogs: 'No admin audit logs yet.', accountHealth: 'Account Health', accountHealthBody: '{inactive} inactive accounts from {total} database users.', reviewUsers: 'Review users', healthCentersTitle: 'Health Center Registry', healthCentersSubtitle: 'Manage healthcare facility data within the system', searchHealthCenter: 'Search health center name...', addHealthCenter: 'Add Health Center', usersTitle: 'User Accounts', usersSubtitle: 'Manage healthcare personnel and IFK officer accounts', addUser: 'Add User', editUser: 'Edit User', medicinesTitle: 'Maternal Medicine Registry', medicinesSubtitle: 'Catalog of {count} maternal medicines used in the system', addMedicine: 'Add Medicine', facilityProfilesTitle: 'Facility Profiles', facilityProfilesSubtitle: 'Logistics and accessibility configuration for each health center', profilesIncomplete: '{count} profiles incomplete'
  }
} satisfies AbstractIntlMessages;

const id = {
  common: { ...en.common, home: 'Beranda', settings: 'Pengaturan', help: 'Bantuan', logout: 'Keluar', language: 'Bahasa', save: 'Simpan', cancel: 'Batal', edit: 'Ubah', delete: 'Hapus', detail: 'Detail', active: 'Aktif', inactive: 'Nonaktif', actions: 'Aksi', status: 'Status', name: 'Nama', role: 'Peran', facility: 'Fasilitas', search: 'Cari', syncingAi: 'Sinkron AI', syncAi: 'Sinkron Master AI' },
  nav: { ...en.nav, dashboard: 'Dasbor', healthCenters: 'Puskesmas', users: 'Akun Pengguna', medicines: 'Daftar Obat', facilityProfiles: 'Profil Fasilitas', patientQueue: 'Antrian Pasien', patients: 'Daftar Pasien', forecastCalendar: 'Kalender Prediksi', medicineNeeds: 'Kebutuhan Obat', ifkDashboard: 'Dasbor IFK', recommendations: 'Rekomendasi', clinics: 'Klinik', environment: 'Lingkungan', decisionHistory: 'Riwayat Keputusan', deliveries: 'Pengiriman' },
  admin: { ...en.admin, settingsTitle: 'Pengaturan Admin', helpTitle: 'Bantuan Admin', settingsSession: 'Cookie login aktif', helpBody: 'Semua data admin tersimpan langsung ke backend. Gunakan tambah, ubah, hapus, sinkronisasi, filter, dan ekspor pada tiap modul.', dashboardTitle: 'Dasbor Admin', dashboardSubtitle: 'Ringkasan master data MaternaLink dari database aktif', lastUpdated: 'Terakhir diperbarui', totalHealthCenters: 'Total Puskesmas', totalUsers: 'Total Pengguna', totalMedicines: 'Total Obat', inactiveAccounts: 'Akun Nonaktif', last30Days: '+{count} / 30 hari', needsReview: 'Perlu review', safe: 'Aman', recentActivity: 'Aktivitas Terbaru', allActivity: 'Semua Aktivitas', loadMoreActivities: 'Muat 10 Aktivitas', noAuditLogs: 'Belum ada audit log admin.', accountHealth: 'Kesehatan Akun', accountHealthBody: '{inactive} akun nonaktif dari {total} pengguna database.', reviewUsers: 'Review user', healthCentersTitle: 'Registri Puskesmas', healthCentersSubtitle: 'Kelola data fasilitas kesehatan dalam sistem', searchHealthCenter: 'Cari nama puskesmas...', addHealthCenter: 'Tambah Puskesmas', usersTitle: 'Akun Pengguna', usersSubtitle: 'Kelola akun tenaga kesehatan dan petugas IFK', addUser: 'Tambah User', editUser: 'Ubah User', medicinesTitle: 'Registri Obat Maternal', medicinesSubtitle: 'Katalog {count} obat maternal yang digunakan sistem', addMedicine: 'Tambah Obat', facilityProfilesTitle: 'Profil Fasilitas', facilityProfilesSubtitle: 'Konfigurasi logistik dan aksesibilitas tiap puskesmas', profilesIncomplete: '{count} profil belum lengkap' }
} satisfies AbstractIntlMessages;

const ms = {
  common: { ...id.common, logout: 'Log keluar', save: 'Simpan', cancel: 'Batal', delete: 'Padam', active: 'Aktif', inactive: 'Tidak aktif' },
  nav: { ...id.nav, dashboard: 'Papan Pemuka', users: 'Akaun Pengguna', medicines: 'Senarai Ubat', facilityProfiles: 'Profil Fasiliti' },
  admin: { ...id.admin, dashboardTitle: 'Papan Pemuka Admin', dashboardSubtitle: 'Ringkasan data induk MaternaLink daripada pangkalan data aktif', addUser: 'Tambah Pengguna', addMedicine: 'Tambah Ubat' }
} satisfies AbstractIntlMessages;

const fil = {
  common: { ...en.common, home: 'Home', settings: 'Mga Setting', help: 'Tulong', logout: 'Mag-logout', language: 'Wika', save: 'I-save', cancel: 'Kanselahin', edit: 'I-edit', delete: 'Tanggalin', detail: 'Detalye', active: 'Aktibo', inactive: 'Hindi aktibo', actions: 'Mga Aksyon', status: 'Katayuan', name: 'Pangalan', role: 'Tungkulin', facility: 'Pasilidad', email: 'Email', username: 'Username', password: 'Password', search: 'Maghanap', syncingAi: 'Sini-sync ang AI Data', syncAi: 'I-sync ang AI Master' },
  nav: { ...en.nav, dashboard: 'Dashboard', healthCenters: 'Mga Health Center', users: 'Mga User Account', medicines: 'Listahan ng Gamot', facilityProfiles: 'Profile ng Pasilidad', patientQueue: 'Pila ng Pasyente', patients: 'Listahan ng Pasyente', forecastCalendar: 'Kalendaryo ng Prediksyon', medicineNeeds: 'Pangangailangan sa Gamot', ifkDashboard: 'IFK Dashboard', recommendations: 'Mga Rekomendasyon', clinics: 'Mga Klinika', environment: 'Kapaligiran', decisionHistory: 'Kasaysayan ng Desisyon', deliveries: 'Paghahatid' },
  admin: { ...en.admin, settingsTitle: 'Mga Setting ng Admin', helpTitle: 'Tulong sa Admin', settingsSession: 'Aktibong login cookie', helpBody: 'Lahat ng admin data ay direktang sine-save sa backend. Gamitin ang add, edit, delete, sync, filter, at export sa bawat module.', dashboardTitle: 'Admin Dashboard', dashboardSubtitle: 'Buod ng master data ng MaternaLink mula sa aktibong database', lastUpdated: 'Huling na-update', totalHealthCenters: 'Kabuuang Health Center', totalUsers: 'Kabuuang User', totalMedicines: 'Kabuuang Gamot', inactiveAccounts: 'Hindi Aktibong Account', last30Days: '+{count} / 30 araw', needsReview: 'Kailangan ng review', safe: 'Ligtas', recentActivity: 'Kamakailang Aktibidad', allActivity: 'Lahat ng Aktibidad', loadMoreActivities: 'Mag-load ng 10 Aktibidad', noAuditLogs: 'Wala pang admin audit log.', accountHealth: 'Kalusugan ng Account', accountHealthBody: '{inactive} hindi aktibong account mula sa {total} database users.', reviewUsers: 'I-review ang users', healthCentersTitle: 'Rehistro ng Health Center', healthCentersSubtitle: 'Pamahalaan ang data ng pasilidad pangkalusugan sa system', searchHealthCenter: 'Hanapin ang pangalan ng health center...', addHealthCenter: 'Magdagdag ng Health Center', usersTitle: 'Mga User Account', usersSubtitle: 'Pamahalaan ang accounts ng healthcare personnel at IFK officer', addUser: 'Magdagdag ng User', editUser: 'I-edit ang User', medicinesTitle: 'Rehistro ng Maternal Medicine', medicinesSubtitle: 'Catalog ng {count} maternal medicines na ginagamit sa system', addMedicine: 'Magdagdag ng Gamot', facilityProfilesTitle: 'Profile ng Pasilidad', facilityProfilesSubtitle: 'Logistics at accessibility configuration para sa bawat health center', profilesIncomplete: '{count} profile ang hindi kumpleto' }
} satisfies AbstractIntlMessages;

const th = {
  common: { ...en.common, home: 'หน้าหลัก', settings: 'ตั้งค่า', help: 'ช่วยเหลือ', logout: 'ออกจากระบบ', language: 'ภาษา', save: 'บันทึก', cancel: 'ยกเลิก', edit: 'แก้ไข', delete: 'ลบ', detail: 'รายละเอียด', active: 'ใช้งาน', inactive: 'ไม่ใช้งาน', actions: 'การดำเนินการ', status: 'สถานะ', name: 'ชื่อ', role: 'บทบาท', facility: 'สถานบริการ', email: 'อีเมล', username: 'ชื่อผู้ใช้', password: 'รหัสผ่าน', search: 'ค้นหา', syncingAi: 'กำลังซิงค์ข้อมูล AI', syncAi: 'ซิงค์ AI Master' },
  nav: { ...en.nav, dashboard: 'แดชบอร์ด', healthCenters: 'ศูนย์สุขภาพ', users: 'บัญชีผู้ใช้', medicines: 'รายการยา', facilityProfiles: 'โปรไฟล์สถานบริการ', patientQueue: 'คิวผู้ป่วย', patients: 'รายชื่อผู้ป่วย', forecastCalendar: 'ปฏิทินคาดการณ์', medicineNeeds: 'ความต้องการยา', ifkDashboard: 'แดชบอร์ด IFK', recommendations: 'คำแนะนำ', clinics: 'คลินิก', environment: 'สิ่งแวดล้อม', decisionHistory: 'ประวัติการตัดสินใจ', deliveries: 'การจัดส่ง' },
  admin: { ...en.admin, superAdmin: 'ผู้ดูแลระบบสูงสุด', settingsTitle: 'ตั้งค่าผู้ดูแลระบบ', helpTitle: 'ช่วยเหลือผู้ดูแลระบบ', settingsSession: 'คุกกี้เข้าสู่ระบบที่ใช้งานอยู่', helpBody: 'ข้อมูลผู้ดูแลระบบทั้งหมดถูกบันทึกไปยัง backend โดยตรง ใช้เพิ่ม แก้ไข ลบ ซิงค์ กรอง และส่งออกในแต่ละโมดูล', dashboardTitle: 'แดชบอร์ดผู้ดูแลระบบ', dashboardSubtitle: 'สรุป master data ของ MaternaLink จากฐานข้อมูลที่ใช้งานอยู่', lastUpdated: 'อัปเดตล่าสุด', totalHealthCenters: 'ศูนย์สุขภาพทั้งหมด', totalUsers: 'ผู้ใช้ทั้งหมด', totalMedicines: 'ยาทั้งหมด', inactiveAccounts: 'บัญชีไม่ใช้งาน', last30Days: '+{count} / 30 วัน', needsReview: 'ต้องตรวจสอบ', safe: 'ปลอดภัย', recentActivity: 'กิจกรรมล่าสุด', allActivity: 'กิจกรรมทั้งหมด', loadMoreActivities: 'โหลดอีก 10 กิจกรรม', noAuditLogs: 'ยังไม่มี audit log ของผู้ดูแลระบบ', accountHealth: 'สถานะบัญชี', accountHealthBody: '{inactive} บัญชีไม่ใช้งาน จากผู้ใช้ฐานข้อมูล {total} คน', reviewUsers: 'ตรวจสอบผู้ใช้', healthCentersTitle: 'ทะเบียนศูนย์สุขภาพ', healthCentersSubtitle: 'จัดการข้อมูลสถานบริการสุขภาพในระบบ', searchHealthCenter: 'ค้นหาชื่อศูนย์สุขภาพ...', addHealthCenter: 'เพิ่มศูนย์สุขภาพ', usersTitle: 'บัญชีผู้ใช้', usersSubtitle: 'จัดการบัญชีบุคลากรสุขภาพและเจ้าหน้าที่ IFK', addUser: 'เพิ่มผู้ใช้', editUser: 'แก้ไขผู้ใช้', medicinesTitle: 'ทะเบียนยามารดา', medicinesSubtitle: 'แคตตาล็อกยาแม่และเด็ก {count} รายการที่ใช้ในระบบ', addMedicine: 'เพิ่มยา', facilityProfilesTitle: 'โปรไฟล์สถานบริการ', facilityProfilesSubtitle: 'การตั้งค่าโลจิสติกส์และการเข้าถึงของแต่ละศูนย์สุขภาพ', profilesIncomplete: '{count} โปรไฟล์ยังไม่ครบถ้วน' }
} satisfies AbstractIntlMessages;

const vi = {
  common: { ...en.common, home: 'Trang chủ', settings: 'Cài đặt', help: 'Trợ giúp', logout: 'Đăng xuất', language: 'Ngôn ngữ', save: 'Lưu', cancel: 'Hủy', edit: 'Sửa', delete: 'Xóa', detail: 'Chi tiết', active: 'Hoạt động', inactive: 'Không hoạt động', actions: 'Thao tác', status: 'Trạng thái', name: 'Tên', role: 'Vai trò', facility: 'Cơ sở', email: 'Email', username: 'Tên đăng nhập', password: 'Mật khẩu', search: 'Tìm kiếm', syncingAi: 'Đang đồng bộ dữ liệu AI', syncAi: 'Đồng bộ AI Master' },
  nav: { ...en.nav, dashboard: 'Bảng điều khiển', healthCenters: 'Trung tâm y tế', users: 'Tài khoản người dùng', medicines: 'Danh sách thuốc', facilityProfiles: 'Hồ sơ cơ sở', patientQueue: 'Hàng đợi bệnh nhân', patients: 'Danh sách bệnh nhân', forecastCalendar: 'Lịch dự báo', medicineNeeds: 'Nhu cầu thuốc', ifkDashboard: 'Bảng điều khiển IFK', recommendations: 'Khuyến nghị', clinics: 'Phòng khám', environment: 'Môi trường', decisionHistory: 'Lịch sử quyết định', deliveries: 'Giao hàng' },
  admin: { ...en.admin, settingsTitle: 'Cài đặt quản trị', helpTitle: 'Trợ giúp quản trị', settingsSession: 'Cookie đăng nhập đang hoạt động', helpBody: 'Tất cả dữ liệu quản trị được lưu trực tiếp vào backend. Dùng thêm, sửa, xóa, đồng bộ, lọc và xuất trong từng module.', dashboardTitle: 'Bảng điều khiển quản trị', dashboardSubtitle: 'Tóm tắt master data MaternaLink từ cơ sở dữ liệu đang hoạt động', lastUpdated: 'Cập nhật lần cuối', totalHealthCenters: 'Tổng trung tâm y tế', totalUsers: 'Tổng người dùng', totalMedicines: 'Tổng thuốc', inactiveAccounts: 'Tài khoản không hoạt động', last30Days: '+{count} / 30 ngày', needsReview: 'Cần xem xét', safe: 'An toàn', recentActivity: 'Hoạt động gần đây', allActivity: 'Tất cả hoạt động', loadMoreActivities: 'Tải thêm 10 hoạt động', noAuditLogs: 'Chưa có audit log quản trị.', accountHealth: 'Tình trạng tài khoản', accountHealthBody: '{inactive} tài khoản không hoạt động trong {total} người dùng database.', reviewUsers: 'Xem xét người dùng', healthCentersTitle: 'Sổ đăng ký trung tâm y tế', healthCentersSubtitle: 'Quản lý dữ liệu cơ sở y tế trong hệ thống', searchHealthCenter: 'Tìm tên trung tâm y tế...', addHealthCenter: 'Thêm trung tâm y tế', usersTitle: 'Tài khoản người dùng', usersSubtitle: 'Quản lý tài khoản nhân viên y tế và cán bộ IFK', addUser: 'Thêm người dùng', editUser: 'Sửa người dùng', medicinesTitle: 'Sổ đăng ký thuốc thai sản', medicinesSubtitle: 'Danh mục {count} thuốc thai sản được dùng trong hệ thống', addMedicine: 'Thêm thuốc', facilityProfilesTitle: 'Hồ sơ cơ sở', facilityProfilesSubtitle: 'Cấu hình logistics và khả năng tiếp cận cho từng trung tâm y tế', profilesIncomplete: '{count} hồ sơ chưa hoàn tất' }
} satisfies AbstractIntlMessages;

const zh = {
  common: { ...en.common, home: '首页', settings: '设置', help: '帮助', logout: '退出登录', language: '语言', save: '保存', cancel: '取消', edit: '编辑', delete: '删除', detail: '详情', active: '启用', inactive: '停用', actions: '操作', status: '状态', name: '名称', role: '角色', facility: '机构', email: '邮箱', username: '用户名', password: '密码', search: '搜索', syncingAi: '正在同步 AI 数据', syncAi: '同步 AI 主数据' },
  nav: { ...en.nav, dashboard: '仪表盘', healthCenters: '卫生中心', users: '用户账号', medicines: '药品列表', facilityProfiles: '机构档案', patientQueue: '患者队列', patients: '患者列表', forecastCalendar: '预测日历', medicineNeeds: '药品需求', ifkDashboard: 'IFK 仪表盘', recommendations: '建议', clinics: '诊所', environment: '环境', decisionHistory: '决策历史', deliveries: '配送' },
  admin: { ...en.admin, superAdmin: '超级管理员', settingsTitle: '管理员设置', helpTitle: '管理员帮助', settingsSession: '当前登录 Cookie', helpBody: '所有管理员数据都会直接保存到后端。请在每个模块中使用新增、编辑、删除、同步、筛选和导出功能。', dashboardTitle: '管理员仪表盘', dashboardSubtitle: '来自当前数据库的 MaternaLink 主数据摘要', lastUpdated: '最后更新', totalHealthCenters: '卫生中心总数', totalUsers: '用户总数', totalMedicines: '药品总数', inactiveAccounts: '停用账号', last30Days: '+{count} / 30 天', needsReview: '需要审核', safe: '安全', recentActivity: '最近活动', allActivity: '全部活动', loadMoreActivities: '再加载 10 条活动', noAuditLogs: '暂无管理员审计日志。', accountHealth: '账号健康度', accountHealthBody: '{total} 个数据库用户中有 {inactive} 个停用账号。', reviewUsers: '审核用户', healthCentersTitle: '卫生中心登记', healthCentersSubtitle: '管理系统中的医疗机构数据', searchHealthCenter: '搜索卫生中心名称...', addHealthCenter: '新增卫生中心', usersTitle: '用户账号', usersSubtitle: '管理医护人员和 IFK 人员账号', addUser: '新增用户', editUser: '编辑用户', medicinesTitle: '孕产药品登记', medicinesSubtitle: '系统使用的 {count} 种孕产药品目录', addMedicine: '新增药品', facilityProfilesTitle: '机构档案', facilityProfilesSubtitle: '配置每个卫生中心的物流和可达性信息', profilesIncomplete: '{count} 个档案未完成' }
} satisfies AbstractIntlMessages;

const km = {
  common: { ...en.common, home: 'ទំព័រដើម', settings: 'ការកំណត់', help: 'ជំនួយ', logout: 'ចាកចេញ', language: 'ភាសា', save: 'រក្សាទុក', cancel: 'បោះបង់', edit: 'កែសម្រួល', delete: 'លុប', detail: 'ព័ត៌មានលម្អិត', active: 'សកម្ម', inactive: 'មិនសកម្ម', actions: 'សកម្មភាព', status: 'ស្ថានភាព', name: 'ឈ្មោះ', role: 'តួនាទី', facility: 'មូលដ្ឋានសេវា', email: 'អ៊ីមែល', username: 'ឈ្មោះអ្នកប្រើ', password: 'ពាក្យសម្ងាត់', search: 'ស្វែងរក', syncingAi: 'កំពុងធ្វើសមកាលកម្មទិន្នន័យ AI', syncAi: 'សមកាលកម្ម AI Master' },
  nav: { ...en.nav, dashboard: 'ផ្ទាំងគ្រប់គ្រង', healthCenters: 'មណ្ឌលសុខភាព', users: 'គណនីអ្នកប្រើ', medicines: 'បញ្ជីថ្នាំ', facilityProfiles: 'ប្រវត្តិមូលដ្ឋានសេវា', patientQueue: 'ជួរអ្នកជំងឺ', patients: 'បញ្ជីអ្នកជំងឺ', forecastCalendar: 'ប្រតិទិនព្យាករ', medicineNeeds: 'តម្រូវការថ្នាំ', ifkDashboard: 'ផ្ទាំង IFK', recommendations: 'អនុសាសន៍', clinics: 'គ្លីនិក', environment: 'បរិស្ថាន', decisionHistory: 'ប្រវត្តិសេចក្តីសម្រេច', deliveries: 'ការដឹកជញ្ជូន' },
  admin: { ...en.admin, superAdmin: 'អ្នកគ្រប់គ្រងខ្ពស់', settingsTitle: 'ការកំណត់អ្នកគ្រប់គ្រង', helpTitle: 'ជំនួយអ្នកគ្រប់គ្រង', settingsSession: 'Cookie ចូលប្រើកំពុងសកម្ម', helpBody: 'ទិន្នន័យអ្នកគ្រប់គ្រងទាំងអស់ត្រូវបានរក្សាទុកទៅ backend ដោយផ្ទាល់។ ប្រើបន្ថែម កែសម្រួល លុប សមកាលកម្ម តម្រង និងនាំចេញក្នុងមូឌុលនីមួយៗ។', dashboardTitle: 'ផ្ទាំងគ្រប់គ្រងអ្នកគ្រប់គ្រង', dashboardSubtitle: 'សង្ខេបទិន្នន័យមេ MaternaLink ពីមូលដ្ឋានទិន្នន័យសកម្ម', lastUpdated: 'បានធ្វើបច្ចុប្បន្នភាពចុងក្រោយ', totalHealthCenters: 'មណ្ឌលសុខភាពសរុប', totalUsers: 'អ្នកប្រើសរុប', totalMedicines: 'ថ្នាំសរុប', inactiveAccounts: 'គណនីមិនសកម្ម', last30Days: '+{count} / 30 ថ្ងៃ', needsReview: 'ត្រូវពិនិត្យ', safe: 'សុវត្ថិភាព', recentActivity: 'សកម្មភាពថ្មីៗ', allActivity: 'សកម្មភាពទាំងអស់', loadMoreActivities: 'ផ្ទុកសកម្មភាព 10 បន្ថែម', noAuditLogs: 'មិនទាន់មាន audit log អ្នកគ្រប់គ្រង។', accountHealth: 'សុខភាពគណនី', accountHealthBody: 'មានគណនីមិនសកម្ម {inactive} ក្នុងចំណោមអ្នកប្រើ database {total}។', reviewUsers: 'ពិនិត្យអ្នកប្រើ', healthCentersTitle: 'បញ្ជីមណ្ឌលសុខភាព', healthCentersSubtitle: 'គ្រប់គ្រងទិន្នន័យមូលដ្ឋានសុខាភិបាលក្នុងប្រព័ន្ធ', searchHealthCenter: 'ស្វែងរកឈ្មោះមណ្ឌលសុខភាព...', addHealthCenter: 'បន្ថែមមណ្ឌលសុខភាព', usersTitle: 'គណនីអ្នកប្រើ', usersSubtitle: 'គ្រប់គ្រងគណនីបុគ្គលិកសុខាភិបាល និងមន្ត្រី IFK', addUser: 'បន្ថែមអ្នកប្រើ', editUser: 'កែសម្រួលអ្នកប្រើ', medicinesTitle: 'បញ្ជីថ្នាំមាតា', medicinesSubtitle: 'កាតាឡុកថ្នាំមាតា {count} ដែលប្រើក្នុងប្រព័ន្ធ', addMedicine: 'បន្ថែមថ្នាំ', facilityProfilesTitle: 'ប្រវត្តិមូលដ្ឋានសេវា', facilityProfilesSubtitle: 'ការកំណត់ឡូជីស្ទិក និងភាពងាយចូលដល់សម្រាប់មណ្ឌលសុខភាពនីមួយៗ', profilesIncomplete: 'ប្រវត្តិ {count} មិនទាន់ពេញលេញ' }
} satisfies AbstractIntlMessages;

const lo = {
  common: { ...en.common, home: 'ໜ້າຫຼັກ', settings: 'ການຕັ້ງຄ່າ', help: 'ຊ່ວຍເຫຼືອ', logout: 'ອອກຈາກລະບົບ', language: 'ພາສາ', save: 'ບັນທຶກ', cancel: 'ຍົກເລີກ', edit: 'ແກ້ໄຂ', delete: 'ລຶບ', detail: 'ລາຍລະອຽດ', active: 'ໃຊ້ງານ', inactive: 'ບໍ່ໃຊ້ງານ', actions: 'ການດຳເນີນການ', status: 'ສະຖານະ', name: 'ຊື່', role: 'ບົດບາດ', facility: 'ສະຖານທີ່ບໍລິການ', email: 'ອີເມວ', username: 'ຊື່ຜູ້ໃຊ້', password: 'ລະຫັດຜ່ານ', search: 'ຄົ້ນຫາ', syncingAi: 'ກຳລັງຊິງຂໍ້ມູນ AI', syncAi: 'ຊິງ AI Master' },
  nav: { ...en.nav, dashboard: 'ແດຊບອດ', healthCenters: 'ສູນສຸຂະພາບ', users: 'ບັນຊີຜູ້ໃຊ້', medicines: 'ລາຍຊື່ຢາ', facilityProfiles: 'ໂປຣໄຟລ໌ສະຖານທີ່', patientQueue: 'ຄິວຄົນເຈັບ', patients: 'ລາຍຊື່ຄົນເຈັບ', forecastCalendar: 'ປະຕິທິນຄາດຄະເນ', medicineNeeds: 'ຄວາມຕ້ອງການຢາ', ifkDashboard: 'ແດຊບອດ IFK', recommendations: 'ຄຳແນະນຳ', clinics: 'ຄລິນິກ', environment: 'ສິ່ງແວດລ້ອມ', decisionHistory: 'ປະຫວັດການຕັດສິນໃຈ', deliveries: 'ການຈັດສົ່ງ' },
  admin: { ...en.admin, superAdmin: 'ຜູ້ຄຸ້ມຄອງສູງສຸດ', settingsTitle: 'ຕັ້ງຄ່າແອດມິນ', helpTitle: 'ຊ່ວຍເຫຼືອແອດມິນ', settingsSession: 'cookie ເຂົ້າລະບົບກຳລັງໃຊ້ງານ', helpBody: 'ຂໍ້ມູນແອດມິນທັງໝົດຖືກບັນທຶກໄປ backend ໂດຍກົງ. ໃຊ້ເພີ່ມ ແກ້ໄຂ ລຶບ ຊິງ ກັ່ນຕອງ ແລະ ສົ່ງອອກໃນແຕ່ລະໂມດູນ.', dashboardTitle: 'ແດຊບອດແອດມິນ', dashboardSubtitle: 'ສະຫຼຸບ master data MaternaLink ຈາກຖານຂໍ້ມູນທີ່ໃຊ້ງານ', lastUpdated: 'ອັບເດດຫຼ້າສຸດ', totalHealthCenters: 'ສູນສຸຂະພາບທັງໝົດ', totalUsers: 'ຜູ້ໃຊ້ທັງໝົດ', totalMedicines: 'ຢາທັງໝົດ', inactiveAccounts: 'ບັນຊີບໍ່ໃຊ້ງານ', last30Days: '+{count} / 30 ມື້', needsReview: 'ຕ້ອງກວດສອບ', safe: 'ປອດໄພ', recentActivity: 'ກິດຈະກຳຫຼ້າສຸດ', allActivity: 'ກິດຈະກຳທັງໝົດ', loadMoreActivities: 'ໂຫຼດອີກ 10 ກິດຈະກຳ', noAuditLogs: 'ຍັງບໍ່ມີ audit log ແອດມິນ.', accountHealth: 'ສຸຂະພາບບັນຊີ', accountHealthBody: 'ມີ {inactive} ບັນຊີບໍ່ໃຊ້ງານ ຈາກຜູ້ໃຊ້ database {total}.', reviewUsers: 'ກວດຜູ້ໃຊ້', healthCentersTitle: 'ທະບຽນສູນສຸຂະພາບ', healthCentersSubtitle: 'ຈັດການຂໍ້ມູນສະຖານບໍລິການສຸຂະພາບໃນລະບົບ', searchHealthCenter: 'ຄົ້ນຫາຊື່ສູນສຸຂະພາບ...', addHealthCenter: 'ເພີ່ມສູນສຸຂະພາບ', usersTitle: 'ບັນຊີຜູ້ໃຊ້', usersSubtitle: 'ຈັດການບັນຊີບຸກຄະລາກອນສຸຂະພາບ ແລະ ເຈົ້າໜ້າທີ່ IFK', addUser: 'ເພີ່ມຜູ້ໃຊ້', editUser: 'ແກ້ໄຂຜູ້ໃຊ້', medicinesTitle: 'ທະບຽນຢາແມ່ແລະເດັກ', medicinesSubtitle: 'ລາຍການຢາແມ່ແລະເດັກ {count} ລາຍການໃນລະບົບ', addMedicine: 'ເພີ່ມຢາ', facilityProfilesTitle: 'ໂປຣໄຟລ໌ສະຖານທີ່', facilityProfilesSubtitle: 'ການຕັ້ງຄ່າໂລຈິສຕິກ ແລະ ການເຂົ້າເຖິງສຳລັບແຕ່ລະສູນສຸຂະພາບ', profilesIncomplete: '{count} ໂປຣໄຟລ໌ຍັງບໍ່ຄົບ' }
} satisfies AbstractIntlMessages;

const my = {
  common: { ...en.common, home: 'ပင်မ', settings: 'ဆက်တင်များ', help: 'အကူအညီ', logout: 'ထွက်ရန်', language: 'ဘာသာစကား', save: 'သိမ်းရန်', cancel: 'မလုပ်တော့ပါ', edit: 'ပြင်ဆင်ရန်', delete: 'ဖျက်ရန်', detail: 'အသေးစိတ်', active: 'အသုံးပြုနေ', inactive: 'အသုံးမပြု', actions: 'လုပ်ဆောင်ချက်များ', status: 'အခြေအနေ', name: 'အမည်', role: 'တာဝန်', facility: 'ဌာန', email: 'အီးမေးလ်', username: 'အသုံးပြုသူအမည်', password: 'စကားဝှက်', search: 'ရှာဖွေ', syncingAi: 'AI ဒေတာ စင့်ခ်လုပ်နေသည်', syncAi: 'AI Master စင့်ခ်လုပ်ရန်' },
  nav: { ...en.nav, dashboard: 'ဒက်ရှ်ဘုတ်', healthCenters: 'ကျန်းမာရေးစင်တာများ', users: 'အသုံးပြုသူအကောင့်များ', medicines: 'ဆေးစာရင်း', facilityProfiles: 'ဌာနပရိုဖိုင်များ', patientQueue: 'လူနာတန်းစီ', patients: 'လူနာစာရင်း', forecastCalendar: 'ခန့်မှန်းပြက္ခဒိန်', medicineNeeds: 'ဆေးလိုအပ်ချက်', ifkDashboard: 'IFK ဒက်ရှ်ဘုတ်', recommendations: 'အကြံပြုချက်များ', clinics: 'ကလင်နစ်များ', environment: 'ပတ်ဝန်းကျင်', decisionHistory: 'ဆုံးဖြတ်ချက်မှတ်တမ်း', deliveries: 'ပို့ဆောင်မှု' },
  admin: { ...en.admin, superAdmin: 'စူပါအက်ဒမင်', settingsTitle: 'အက်ဒမင်ဆက်တင်များ', helpTitle: 'အက်ဒမင်အကူအညီ', settingsSession: 'အသုံးပြုနေသော login cookie', helpBody: 'အက်ဒမင်ဒေတာအားလုံးကို backend သို့ တိုက်ရိုက်သိမ်းဆည်းထားသည်။ Module တစ်ခုချင်းစီတွင် add, edit, delete, sync, filter, export ကို အသုံးပြုပါ။', dashboardTitle: 'အက်ဒမင်ဒက်ရှ်ဘုတ်', dashboardSubtitle: 'အသုံးပြုနေသော database မှ MaternaLink master data အကျဉ်းချုပ်', lastUpdated: 'နောက်ဆုံးအပ်ဒိတ်', totalHealthCenters: 'ကျန်းမာရေးစင်တာ စုစုပေါင်း', totalUsers: 'အသုံးပြုသူ စုစုပေါင်း', totalMedicines: 'ဆေး စုစုပေါင်း', inactiveAccounts: 'အသုံးမပြုသောအကောင့်များ', last30Days: '+{count} / 30 ရက်', needsReview: 'စစ်ဆေးရန်လိုသည်', safe: 'လုံခြုံ', recentActivity: 'မကြာသေးမီ လုပ်ဆောင်ချက်', allActivity: 'လုပ်ဆောင်ချက်အားလုံး', loadMoreActivities: 'နောက်ထပ် 10 ခုတင်ရန်', noAuditLogs: 'အက်ဒမင် audit log မရှိသေးပါ။', accountHealth: 'အကောင့်အခြေအနေ', accountHealthBody: 'database အသုံးပြုသူ {total} ယောက်ထဲမှ {inactive} အကောင့် အသုံးမပြုပါ။', reviewUsers: 'အသုံးပြုသူ စစ်ဆေးရန်', healthCentersTitle: 'ကျန်းမာရေးစင်တာမှတ်ပုံတင်', healthCentersSubtitle: 'စနစ်အတွင်းရှိ ကျန်းမာရေးဌာနဒေတာကို စီမံပါ', searchHealthCenter: 'ကျန်းမာရေးစင်တာအမည် ရှာရန်...', addHealthCenter: 'ကျန်းမာရေးစင်တာ ထည့်ရန်', usersTitle: 'အသုံးပြုသူအကောင့်များ', usersSubtitle: 'ကျန်းမာရေးဝန်ထမ်းနှင့် IFK ဝန်ထမ်းအကောင့်များကို စီမံပါ', addUser: 'အသုံးပြုသူ ထည့်ရန်', editUser: 'အသုံးပြုသူ ပြင်ရန်', medicinesTitle: 'မိခင်ဆေးမှတ်ပုံတင်', medicinesSubtitle: 'စနစ်တွင်အသုံးပြုသော မိခင်ဆေး {count} မျိုး စာရင်း', addMedicine: 'ဆေး ထည့်ရန်', facilityProfilesTitle: 'ဌာနပရိုဖိုင်များ', facilityProfilesSubtitle: 'ကျန်းမာရေးစင်တာတိုင်းအတွက် logistics နှင့် accessibility ဆက်တင်များ', profilesIncomplete: 'ပရိုဖိုင် {count} ခု မပြီးသေးပါ' }
} satisfies AbstractIntlMessages;

const ta = {
  common: { ...en.common, home: 'முகப்பு', settings: 'அமைப்புகள்', help: 'உதவி', logout: 'வெளியேறு', language: 'மொழி', save: 'சேமி', cancel: 'ரத்து', edit: 'திருத்து', delete: 'நீக்கு', detail: 'விவரம்', active: 'செயலில்', inactive: 'செயலில் இல்லை', actions: 'செயல்கள்', status: 'நிலை', name: 'பெயர்', role: 'பங்கு', facility: 'வசதி', email: 'மின்னஞ்சல்', username: 'பயனர்பெயர்', password: 'கடவுச்சொல்', search: 'தேடு', syncingAi: 'AI தரவு ஒத்திசைக்கிறது', syncAi: 'AI Master ஒத்திசை' },
  nav: { ...en.nav, dashboard: 'டாஷ்போர்டு', healthCenters: 'சுகாதார மையங்கள்', users: 'பயனர் கணக்குகள்', medicines: 'மருந்து பட்டியல்', facilityProfiles: 'வசதி சுயவிவரங்கள்', patientQueue: 'நோயாளர் வரிசை', patients: 'நோயாளர் பட்டியல்', forecastCalendar: 'முன்கணிப்பு நாட்காட்டி', medicineNeeds: 'மருந்து தேவைகள்', ifkDashboard: 'IFK டாஷ்போர்டு', recommendations: 'பரிந்துரைகள்', clinics: 'மருத்துவமனைகள்', environment: 'சூழல்', decisionHistory: 'முடிவு வரலாறு', deliveries: 'விநியோகம்' },
  admin: { ...en.admin, superAdmin: 'சூப்பர் அட்மின்', settingsTitle: 'அட்மின் அமைப்புகள்', helpTitle: 'அட்மின் உதவி', settingsSession: 'செயலில் உள்ள உள்நுழைவு cookie', helpBody: 'அனைத்து அட்மின் தரவும் backend இல் நேரடியாக சேமிக்கப்படுகிறது. ஒவ்வொரு module-இலும் add, edit, delete, sync, filter, export செயல்களைப் பயன்படுத்தவும்.', dashboardTitle: 'அட்மின் டாஷ்போர்டு', dashboardSubtitle: 'செயலில் உள்ள database இலிருந்து MaternaLink master data சுருக்கம்', lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது', totalHealthCenters: 'மொத்த சுகாதார மையங்கள்', totalUsers: 'மொத்த பயனர்கள்', totalMedicines: 'மொத்த மருந்துகள்', inactiveAccounts: 'செயலில் இல்லாத கணக்குகள்', last30Days: '+{count} / 30 நாட்கள்', needsReview: 'மதிப்பாய்வு தேவை', safe: 'பாதுகாப்பானது', recentActivity: 'சமீபத்திய செயல்பாடு', allActivity: 'அனைத்து செயல்பாடுகள்', loadMoreActivities: 'மேலும் 10 செயல்பாடுகள் ஏற்று', noAuditLogs: 'அட்மின் audit log இன்னும் இல்லை.', accountHealth: 'கணக்கு நிலை', accountHealthBody: '{total} database பயனர்களில் {inactive} கணக்குகள் செயலற்றவை.', reviewUsers: 'பயனர்களை மதிப்பாய்வு செய்', healthCentersTitle: 'சுகாதார மைய பதிவு', healthCentersSubtitle: 'அமைப்பில் உள்ள சுகாதார வசதி தரவை நிர்வகிக்கவும்', searchHealthCenter: 'சுகாதார மைய பெயரை தேடு...', addHealthCenter: 'சுகாதார மையம் சேர்', usersTitle: 'பயனர் கணக்குகள்', usersSubtitle: 'சுகாதார பணியாளர்கள் மற்றும் IFK அதிகாரி கணக்குகளை நிர்வகிக்கவும்', addUser: 'பயனர் சேர்', editUser: 'பயனர் திருத்து', medicinesTitle: 'தாய்மை மருந்து பதிவு', medicinesSubtitle: 'அமைப்பில் பயன்படுத்தப்படும் {count} தாய்மை மருந்துகளின் பட்டியல்', addMedicine: 'மருந்து சேர்', facilityProfilesTitle: 'வசதி சுயவிவரங்கள்', facilityProfilesSubtitle: 'ஒவ்வொரு சுகாதார மையத்திற்கும் logistics மற்றும் accessibility அமைப்பு', profilesIncomplete: '{count} சுயவிவரங்கள் முழுமையில்லை' }
} satisfies AbstractIntlMessages;

const dictionaries: Partial<Record<AppLocale, AbstractIntlMessages>> = {
  en,
  id,
  ms,
  fil,
  th,
  vi,
  km,
  lo,
  my,
  zh,
  ta,
};

export function getMessages(locale: AppLocale): AbstractIntlMessages {
  return dictionaries[locale] ?? dictionaries[defaultLocale] ?? en;
}
