export const routes = {
  login: '/login',
  admin: '/admin',
  adminHealthCenters: '/admin/health-centers',
  adminUsers: '/admin/users',
  adminMedicines: '/admin/medicines',
  adminFacilityProfiles: '/admin/facility-profiles',
  dashboard: '/dashboard',
  patients: '/patients',
  patientDetail: (id: string) => `/patients/${encodeURIComponent(id)}`,
  newPatient: '/patients/new',
  manualPatient: '/patients/new/manual',
  queue: '/queue',
  examination: '/queue/examination',
  forecastCalendar: '/forecast-calendar',
  medicineNeeds: '/medicine-needs',
  deliveries: '/deliveries',
  ifk: '/ifk',
  ifkRecommendations: '/ifk/recommendations',
  ifkDecisionHistory: '/ifk/decision-history',
  ifkClinics: '/ifk/clinics',
  ifkEnvironment: '/ifk/environment',
} as const;
